### ISSUE TITLE
createProject0.sh: problems with spaces in directory name

### ISSUE THREAD

**Issue by Bounnoy** [JoyOfCodingPDX/GettingStarted#1]
I ran the command: `./createProject0.sh bounnoy`

It gives the output:
> macPro:PortlandStateJavaGettingStarted Bounnoy$ ./createProject0.sh bounnoy
> /usr/bin/java
> Found java executable in execution PATH
> You are running Java version 12.0.1
> This version of Java is sufficient for this course
> checkForJava.sh: line 37: [: /Users/Bounnoy: binary operator expected
> grep: /Users/Bounnoy: Is a directory
> grep: 1/.m2/settings.xml: No such file or directory
> ** Your settings.xml file does not contain https://dl.bintray.com/davidwhitlock/maven
> ** Please place information from local settings.xml into /Users/Bounnoy 1/.m2/settings.xml
> ** Your Maven settings are not configured correctly in your environment

I think it's due to my home directory having a space in it.
I already copied settings.xml over to the .m2 directory.

**Comment by Bounnoy** [comment]
When I moved to a new Macbook it made a new home directory with an extra space followed by a 1.
Kinda annoyed me and knew it would one day cause a problem, lol.
I just finished changing my home directory name and now the command is working just fine.
Just thought I'd let you know.

**Comment by DavidWhitlock** [comment]
I added some double quotes around the reference to the `settings.xml` file in the user's home directory.  @Bounnoy, could you try it out to see if works for you?

**Comment by DavidWhitlock** [comment]
Now that the `createFirstProject.sh` script can only be run on the PSU Linux machines, it's very unlikely that this problem will reoccur.  I'm going to close this issue.
